TriviaCrack/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace TriviaCrack.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

TriviaCrack/Views/Shared/Error.Mobile.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Error";
}

<style>
    * {
        font-family: Verdana;
        color: red;
    }

    h1, h2 {
        text-indent: 5px;
    }
</style>
<h1>Error!</h1>
<h2>An error occurred while processing your request.</h2>

TriviaCrack/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
    @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .topnav {
          background-color: black;
          overflow: hidden;
          width: auto;
          font-family: Verdana;
          font-weight: bold;
        }

        .topnav a, .dropdown-btn  {
          float: left;
          display: block;
          color: white;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
          font-size: 17px;
        }

        .topnav a:not(:first-child) {display: none;}
        .topnav a.icon {
          float: right;
          display: block;
       }

       .topnav.responsive {position: relative;}
       .topnav.responsive a.icon {
         position: absolute;
         right: 0;
         top: 0;
       }
       .topnav.responsive a {
         float: none;
         display: block;
         text-align: left;
       }
      
        .active {
            background-color: green;
            color: white;
        }

        .dropdown-container {
            display: none;
            background-color: #262626;
            padding-left: 8px;
        }

        .fa-caret-down {
            float: right;
            padding-right: 8px;
        }
    </style>
    <script>
        $(document).ready(function () {
            $.mobile.ajaxEnabled = false;
        });

        function myFunction() {
            var x = document.getElementById("myTopnav");
            if (x.className === "topnav") {
                x.className += " responsive";
            } else {
                x.className = "topnav";
            }
        }
    </script>
</head>
<body>

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <!--<h1>ViewBag.Title</h1>-->
            <br />
        </div>
        <div class="topnav" id="myTopnav">
            @Html.ActionLink("Trivia Crackle", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            @if (User.IsInRole("Administrator"))
            {
                <a class="dropdown-btn">Administration<i class="fa fa-caret-down"></i></a>
                <div class="dropdown-container" id="myAdmin" style="display: none">
                @Html.ActionLink("Users", "Index", "Admin")<span class="glyphicon glyphicon-user"></span>
                @Html.ActionLink("Categories", "Index", "Category")<span class="glyphicon glyphicon-user"></span>
                @Html.ActionLink("Questions", "Index", "Question")<span class="glyphicon glyphicon-user"></span>
                @Html.ActionLink("Generate Questions", "Questions", "Generator")<span class="glyphicon glyphicon-user"></span>
                @Html.ActionLink("Submitted Questions", "Index", "SubmittedQuestions")<span class="glyphicon glyphicon-user"></span>
                </div>
                @Html.ActionLink("Site Statistics", "Index", "Statistics")<span class="glyphicon glyphicon-signal"></span>
                @Html.ActionLink("Help","Help", "Home")<span class="glyphicon glyphicon-exclamation-sign"></span>
            }
            else
            {
                @Html.ActionLink("Submit a Question", "Create", "SubmittedQuestions")<span class="glyphicon glyphicon-question-sign"></span>
                @Html.ActionLink("Site Statistics", "Index", "Statistics")<span class="glyphicon glyphicon-signal"></span>
                @Html.ActionLink("Help", "Help", "Home")<span class="glyphicon glyphicon-exclamation-sign"></span>
            }
            <!--<a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>-->
            <img src="@Url.Action("UserPhotos", "Home" )" height="33" width="35" style="margin-top: 8px; margin-right: 8px; float: right;" onclick="myFunction()"/>
            @Html.Partial("_LoginPartial.Mobile")
        </div>
        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()
        </div>

        <div data-role="footer">
            <hr />
            <p style="font-family: Verdana">&copy; @DateTime.Now.Year - Trivia Crackle</p>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("Styles", required: false)

    <script>
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }
    </script>
</body>
</html>

TriviaCrack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Trivia Crackle</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Trivia Crackle", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   @if (User.IsInRole("Administrator"))
                    {
                        <li><a href="@Url.Action("Index", "Admin")"><span class="glyphicon glyphicon-user"></span> Administration</a></li>
                        <li><a href="@Url.Action("Index", "Statistics")"><span class="glyphicon glyphicon-signal"></span> Site Statistics</a></li>
                        <li><a href="@Url.Action("Help", "Home")"><span class="glyphicon glyphicon-exclamation-sign"></span> Help</a></li>
                   }
                   else
                   {
                        <li><a href="@Url.Action("Create", "SubmittedQuestions")"><span class="glyphicon glyphicon-question-sign"></span> Submit a Question</a></li>
                        <li><a href="@Url.Action("Index", "Statistics")"><span class="glyphicon glyphicon-signal"></span> Site Statistics</a></li>
                        <li><a href="@Url.Action("Help", "Home")"><span class="glyphicon glyphicon-exclamation-sign"></span> Help</a></li>
                   }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
<div class="container body-content">
    <div>
        @RenderBody()
    </div>
    <hr/>
    <div>
        <footer>
            <p>&copy; @DateTime.Now.Year - Trivia Crackle</p>
        </footer>
    </div>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("Styles", required: false)
</body>
</html>

TriviaCrack/Views/Shared/_LoginPartial.Mobile.cshtml
@using Microsoft.AspNet.Identity
@{ 
    var level = 0;
    if (ViewData["level"] == null)
    {
        level = 0;
    } else {
        level = (int)ViewData["level"];
    }
}
@if (Request.IsAuthenticated)
{

    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
    @Html.AntiForgeryToken()    
        @Html.ActionLink(User.Identity.GetUserName(), "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage"})
        <a href="javascript:document.getElementById('logoutForm').submit()"><span class="glyphicon glyphicon-log-in"></span>Logout</a>
    }
}
else
{
       @Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })<span class="glyphicon glyphicon-user"></span>
       @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })<span class="glyphicon glyphicon-log-in"></span>
}

TriviaCrack/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}